language: python
python: 3.4

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  - TOXENV=py34 TOXARGS="-- --dbfixtures-config .travis/dbfixtures.conf"
  - TOXENV=pep8
  - TOXENV=docs
  - TOXENV=packaging
  - TOXENV=translations

install: pip install -U pip wheel tox codecov

script: tox $TOXARGS

after_success: codecov

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
