language: python
python: 3.4

addons:
  postgresql: "9.4"

env:
  - TOXENV=py34
  - TOXENV=pep8
  - TOXENV=docs
  - TOXENV=packaging

install: pip install tox

script: tox

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
