language: python
python: 3.5.0

dist: trusty

sudo: false

cache:
  directories:
    - ~/.cache/pip

install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements/docs.txt -r requirements/lint.txt -r requirements/main.txt -r requirements/tests.txt

script: bin/tests --dbfixtures-config tests/dbfixtures.travis.conf

matrix:
  include:
    - script: make lint BINDIR="$(dirname $(which python))"
    - script: make docs BINDIR="$(dirname $(which python))"

after_success: codecov

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
