language: python
python: 3.5.0

dist: trusty

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  - TOXENV=py35 TOXARGS="-- --dbfixtures-config .travis/dbfixtures.conf"
  - TOXENV=pep8
  - TOXENV=docs
  - TOXENV=packaging
  - TOXENV=translations

install:
  - pip install -U pip
  - pip install -U wheel tox codecov

script: tox $TOXARGS

after_success: codecov

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
