serve:
  workers: 1

include:
  pyramid_debugtoolbar: True

configurator:
  database:
    url: "postgresql://localhost/warehouse"

  sessions:
    secret: "an insecure development secret"
    url: "redis://localhost:6379/0"

  debugtoolbar:
    panels:
      - pyramid_debugtoolbar.panels.versions.VersionDebugPanel
      - pyramid_debugtoolbar.panels.settings.SettingsDebugPanel
      - pyramid_debugtoolbar.panels.headers.HeaderDebugPanel
      - pyramid_debugtoolbar.panels.request_vars.RequestVarsDebugPanel
      - pyramid_debugtoolbar.panels.renderings.RenderingsDebugPanel
      - pyramid_debugtoolbar.panels.logger.LoggingPanel
      - pyramid_debugtoolbar.panels.performance.PerformanceDebugPanel
      - pyramid_debugtoolbar.panels.routes.RoutesDebugPanel
      - pyramid_debugtoolbar.panels.sqla.SQLADebugPanel
      - pyramid_debugtoolbar.panels.tweens.TweensDebugPanel
      - pyramid_debugtoolbar.panels.introspection.IntrospectionDebugPanel

  pyramid:
    reload_assets: True
    reload_templates: True
